name: Linkcheck
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the action
        uses: TechWiz-3/linksafe@main
        with:
          whitelist_files: "CONTRIBUTING.md"
          whitelist_links: "https://www.lfd.uci.edu/~gohlke/pythonlibs/,http://www.rdkit.org/,https://www.docker.com/,https://www.linkedin.com/in/vinta"
